language: python
dist: xenial
os: linux
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
notifications:
  email: datasnakes@gmail.com
# command to install dependencies
install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --only-binary=numpy,scipy numpy scipy"
  - "pip install matplotlib ipython jupyter sympy pytest"
  - "pip install -r requirements.txt"
<<<<<<< HEAD
  - "pip install ."
# command to run unittests via pytest
script:
  - pytest tests/
=======
# command to run unittests
script: pytest tests
>>>>>>> e4766d7... Add pytest to .travis.yml.
