language: python
cache: pip
python:
  - "3.5"
  - "3.6"
notifications:
  email: datasnakes@gmail.com
# command to install dependencies
before_install:
  - sudo apt-get install -qq phyml
install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --only-binary=numpy,scipy numpy scipy"
  - "pip install ipython jupyter sympy nose"
  - "pip install -r requirements.txt"
# command to run nosetests
script:
  - nosetests tests/ --verbosity=3
